//*****************Auth *******************/
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL ";


export const BUDGET_START = "BUDGET_START";
export const BUDGET_SUCCESS = "BUDGET_SUCCESS";
export const BUDGET_FAIL = "BUDGET_FAIL ";

export const ADD_BUDGET = "ADD_BUDGET";

export const PRODUCT_GET_START = "PRODUCT_GET_START";
export const PRODUCT_GET_SUCCESS = "PRODUCT_GET_SUCCESS";
export const PRODUCT_GET_FAIL = "PRODUCT_GET_FAIL";


export const PRODUCT_POST_START = "PRODUCT_POST_START";
export const PRODUCT_POST_SUCCESS = "PRODUCT_POST_SUCCESS";
export const PRODUCT_POST_FAIL = "PRODUCT_POST_FAIL";


export const PRODUCT_PATCH_START = "PRODUCT_PATCH_START";
export const PRODUCT_PATCH_SUCCESS = "PRODUCT_PATCH_SUCCESS";
export const PRODUCT_PATCH_FAIL = "PRODUCT_PATCH_FAIL";


